### ISSUE TITLE
Trabajando con validators

### ISSUE THREAD

**Issue by Isabel9422** [Open-Bootcamp/movie-app-API#1]
1. Crear los siguientes **validators** para las entidades _Imagen_ y _Content_:
  - CreateEntidadValidator
  - UpdateEntidadValidator

2. Modificar métodos del **controller** para validar data a la hora de **create** and **update**.
3. Método en el _ContentsController_ que devuelva _contents_ asociados a las _imágenes_.

**Comment by PabloHurtadoGonzalo86** [comment]
Isa creo que esta completada
