### ISSUE TITLE
Terminar Validators - Nueva entidad: User

### ISSUE THREAD

**Issue by Isabel9422** [Open-Bootcamp/movie-app-API#2]
1. Validator para ordenar la data _content_ a la hora de hacer uso del método **index**:
   - SortEntidadValidator

2. Investigar **auth** AdonisJs
   - Crear entidad _User_ (campos: ursername, email, password and token)
   - CRUD **_Users_**

**Comment by PabloHurtadoGonzalo86** [comment]
completado
